require:
  - rubocop-rake

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Include:
    - 2.6
    - 2.7
    - 3.0

Layout/LineLength:
  Max: 140

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Max: 120

Security/YAMLLoad:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EachWithObject:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
